# Generated by Django 5.2.8 on 2025-12-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_course_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offer_text',
            field=models.CharField(default='Limited Time Discount', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(default='Limited Time Discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userprofile')),
            ],
        ),
    ]
